//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAnalisis.WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.LogicaBDSoap")]
    public interface LogicaBDSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WAnalisis.WS.HelloWorldResponse HelloWorld(WAnalisis.WS.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WAnalisis.WS.HelloWorldResponse> HelloWorldAsync(WAnalisis.WS.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento User del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarClave", ReplyAction="*")]
        WAnalisis.WS.ConsultarClaveResponse ConsultarClave(WAnalisis.WS.ConsultarClaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarClave", ReplyAction="*")]
        System.Threading.Tasks.Task<WAnalisis.WS.ConsultarClaveResponse> ConsultarClaveAsync(WAnalisis.WS.ConsultarClaveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WAnalisis.WS.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WAnalisis.WS.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAnalisis.WS.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WAnalisis.WS.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarClaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarClave", Namespace="http://tempuri.org/", Order=0)]
        public WAnalisis.WS.ConsultarClaveRequestBody Body;
        
        public ConsultarClaveRequest() {
        }
        
        public ConsultarClaveRequest(WAnalisis.WS.ConsultarClaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarClaveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        public ConsultarClaveRequestBody() {
        }
        
        public ConsultarClaveRequestBody(string User, string Pass) {
            this.User = User;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarClaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarClaveResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAnalisis.WS.ConsultarClaveResponseBody Body;
        
        public ConsultarClaveResponse() {
        }
        
        public ConsultarClaveResponse(WAnalisis.WS.ConsultarClaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarClaveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarClaveResult;
        
        public ConsultarClaveResponseBody() {
        }
        
        public ConsultarClaveResponseBody(string ConsultarClaveResult) {
            this.ConsultarClaveResult = ConsultarClaveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogicaBDSoapChannel : WAnalisis.WS.LogicaBDSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogicaBDSoapClient : System.ServiceModel.ClientBase<WAnalisis.WS.LogicaBDSoap>, WAnalisis.WS.LogicaBDSoap {
        
        public LogicaBDSoapClient() {
        }
        
        public LogicaBDSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogicaBDSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogicaBDSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogicaBDSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAnalisis.WS.HelloWorldResponse WAnalisis.WS.LogicaBDSoap.HelloWorld(WAnalisis.WS.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WAnalisis.WS.HelloWorldRequest inValue = new WAnalisis.WS.HelloWorldRequest();
            inValue.Body = new WAnalisis.WS.HelloWorldRequestBody();
            WAnalisis.WS.HelloWorldResponse retVal = ((WAnalisis.WS.LogicaBDSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WAnalisis.WS.HelloWorldResponse> WAnalisis.WS.LogicaBDSoap.HelloWorldAsync(WAnalisis.WS.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WAnalisis.WS.HelloWorldResponse> HelloWorldAsync() {
            WAnalisis.WS.HelloWorldRequest inValue = new WAnalisis.WS.HelloWorldRequest();
            inValue.Body = new WAnalisis.WS.HelloWorldRequestBody();
            return ((WAnalisis.WS.LogicaBDSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAnalisis.WS.ConsultarClaveResponse WAnalisis.WS.LogicaBDSoap.ConsultarClave(WAnalisis.WS.ConsultarClaveRequest request) {
            return base.Channel.ConsultarClave(request);
        }
        
        public string ConsultarClave(string User, string Pass) {
            WAnalisis.WS.ConsultarClaveRequest inValue = new WAnalisis.WS.ConsultarClaveRequest();
            inValue.Body = new WAnalisis.WS.ConsultarClaveRequestBody();
            inValue.Body.User = User;
            inValue.Body.Pass = Pass;
            WAnalisis.WS.ConsultarClaveResponse retVal = ((WAnalisis.WS.LogicaBDSoap)(this)).ConsultarClave(inValue);
            return retVal.Body.ConsultarClaveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WAnalisis.WS.ConsultarClaveResponse> WAnalisis.WS.LogicaBDSoap.ConsultarClaveAsync(WAnalisis.WS.ConsultarClaveRequest request) {
            return base.Channel.ConsultarClaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<WAnalisis.WS.ConsultarClaveResponse> ConsultarClaveAsync(string User, string Pass) {
            WAnalisis.WS.ConsultarClaveRequest inValue = new WAnalisis.WS.ConsultarClaveRequest();
            inValue.Body = new WAnalisis.WS.ConsultarClaveRequestBody();
            inValue.Body.User = User;
            inValue.Body.Pass = Pass;
            return ((WAnalisis.WS.LogicaBDSoap)(this)).ConsultarClaveAsync(inValue);
        }
    }
}
